name: Fly Deploy Showcase
on:
  push:
    branches:
      - showcase
    paths:
      - "schema/**"
      - "schema-js/**"
      - "backend/**"
      - "frontend/**"
      - "fly.toml"
      - "docs/**"
jobs:
  deploy:
    name: Deploy showcase
    runs-on: ubuntu-latest
    concurrency: deploy-showcase
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
